### ISSUE TITLE
Which Refined GitHub features don't work?

### ISSUE THREAD

**Issue by sberrevoets** [lautis/refined-github-safari#3]
After your update I can definitely tell that the extension is loaded, as many features are now available again. However, I'm also missing a few that were available before, such as full names in comments and seeing who reacted to a comment at a glance. I noticed you hardcoded some disabled features, but these didn't seem to be part of that list.

Are you aware of which features don't work, and why not? Happy to help fix them, but not sure where to start since it seems to be pretty arbitrary.

**Comment by lautis** [comment]
I know of two, which have been disabled:

* show-recently-pushed-branches-on-more-pages
* split-issue-pr-search-results

These crash Safari. I'm not sure why, but it seems to happen whenever the extension uses `<include>` tag.

Then there might be others that don't work because they use the GraphQL API that requires API token. To test whether a missing feature is indeed because of this, you could add an API token to https://github.com/lautis/refined-github-safari/blob/master/Refined%20GitHub%20Extension/SafariExtensionHandler.swift#L44

```
let options = [
            "disabledFeatures": "show-recently-pushed-branches-on-more-pages split-issue-pr-search-results",
            "personalToken": "GITHUB-API-TOKEN"
        ]
```

**Comment by sberrevoets** [comment]
Ah perfect! I did see a note somewhere where you mentioned a missing token, but I'll just insert that myself for now.

For what it's worth, if you can get a list of current problems or missing features you're aware of compiled somewhere, I can try to dedicate some time to help fixing these.

**Comment by lautis** [comment]
Created issues for the known missing features/problems.

**Comment by sberrevoets** [comment]
Sounds good, thanks!
